export const REWARD_TYPES_MAP = {
  INVITATION_BONUS: "INVITATION BONUS",
  SIGNUP_BONUS: "SIGNUP BONUS",
  ATTENDANCE_BONUS: "ATTENDANCE BONUS",
  FIRST_RECHARGE_BONUS: "FIRST RECHARGE BONUS",
  DAILY_RECHARGE_BONUS: "DAILY RECHARGE BONUS",
  FIRST_RECHARGE_AGENT_BONUS: "FIRST RECHARGE AGENT BONUS",
  DAILY_RECHARGE_AGENT_BONUS: "DAILY RECHARGE AGENT BONUS",
  VIP_LEVEL_UP_BONUS: "VIP LEVEL UP BONUS",
  VIP_MONTHLY_REWARD: "VIP MONTHLY REWARD",
  DAILY_BETTING_BONUS: "DAILY BETTING BONUS",
  WEEKLY_BETTING_BONUS: "WEEKLY BETTING BONUS",
  ROI_STAKE_1: "ROI STAKE 1 MONTH",
  ROI_STAKE_3: "ROI STAKE 3 MONTH",
  ROI_STAKE_6: "ROI STAKE 6 MONTH",
  ROI_STAKE_12: "ROI STAKE 12 MONTHS",
  REBATE_BONUS: "DAILY REBATE BONUS",
};

export const REWARD_STATUS_TYPES_MAP = {
  SUCCESS: 1,
  LOCKED: 2,
};
